version: '3.4'

services:
  webapplication1:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - REDIS_URL=redis://redis:6379
    ports:
      - "5000:5000"
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"